simplify room mechanism
cc-schueler-praktika/softwarebude pull request #11
Opened 2020-02-14 15:44 UTC by BeniRupp

Add generic mechanism for locked room doors and room intros.
A task can have a timer, now.

2020-02-14 15:59 UTC, RSchlenker requested changes

2020-02-14 15:59 UTC, RSchlenker commented on softwarebude/escape_room.py
> +            "Eigentlich hast du keine anderer Möglichkeit. Dafür bezahle ich dich schließlich."
Fix Typo "keine andere Möglichkeit"

2020-02-14 15:59 UTC, RSchlenker commented on softwarebude/task.py
> +            return True
Maybe we can use a more expressive method name here? Like: is_time_to_answer_left(self) or answer_time_left() or still_time_to_answer()

2020-02-14 15:59 UTC, RSchlenker commented on softwarebude/treasure_room.py
> +        print("...eine Gehaltserhöhung! Du bekommst mehr Geld. 💸")
Are these icons unix compatible?

2020-02-14 16:39 UTC, BeniRupp commented on softwarebude/treasure_room.py
> +        print("...eine Gehaltserhöhung! Du bekommst mehr Geld. 💸")
You can add an issue for that. 🙂

2020-02-17 07:08 UTC, RSchlenker approved these changes

2020-02-17 07:08 UTC, merged